version: "3.7"
services:
  ng-route-providers:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        HOST_USER_ID: ${HOST_USER_ID:-1000}
        HOST_GROUP_ID: ${HOST_GROUP_ID:-1000}
    ports:
      - ${SERVER_PORT:-4200}:4200
    volumes:
      - ./:/app
    command: /bin/sh -c 'npm install && ng serve --host="0.0.0.0"'

